# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: gecko_taskgraph.loader.transform:loader

kind-dependencies:
    - toolchain
    - build

transforms:
    - gecko_taskgraph.transforms.job:transforms
    - gecko_taskgraph.transforms.task:transforms

job-defaults:
    attributes:
        retrigger: true
    run-on-projects: ['integration', 'release']
    treeherder:
        tier: 1
        kind: other
    worker:
        max-run-time: 3600
        env:
            RUST_BACKTRACE: 'full'
            RUSTFLAGS: '--deny warnings'
    run:
        sparse-profile: webrender

jobs:
    lint-tidy:
        description: Runs linting checks on WebRender code
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: webrender}
        run:
            using: run-task
            cwd: '{checkout}/gfx/wr'
            command: >-
                servo-tidy
        treeherder:
            platform: linux64-qr/opt
            symbol: WR(tidy)
        when:
            files-changed:
                - 'gfx/wr/**'

    linux64-release:
        description: Runs release-mode WebRender CI tests on a Linux worker
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: webrender}
        fetches:
            toolchain:
                - linux64-rust
                - wrench-deps
        run:
            using: run-task
            command: >-
                export PATH=$PATH:$MOZ_FETCHES_DIR/rustc/bin:${MOZ_FETCHES_DIR}/wrench-deps/meson &&
                cd $HOME/checkouts/gecko/gfx/wr &&
                mv $MOZ_FETCHES_DIR/wrench-deps/{vendor,.cargo} ./ &&
                CARGOFLAGS="--verbose --frozen" ci-scripts/linux-release-tests.sh
        treeherder:
            platform: linux64-qr/opt
            symbol: WR(wrench)
            kind: other
        when:
            files-changed:
                - 'gfx/wr/**'

    linux64-debug:
        description: Runs debug-mode WebRender CI tests on a Linux worker
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: webrender}
        fetches:
            toolchain:
                - linux64-rust
                - wrench-deps
        run:
            using: run-task
            command: >-
                export PATH=$PATH:$MOZ_FETCHES_DIR/rustc/bin:${MOZ_FETCHES_DIR}/wrench-deps/meson &&
                cd $HOME/checkouts/gecko/gfx/wr &&
                mv $MOZ_FETCHES_DIR/wrench-deps/{vendor,.cargo} ./ &&
                CARGOFLAGS="--verbose --frozen" ci-scripts/linux-debug-tests.sh
        treeherder:
            platform: linux64-qr/debug
            symbol: WR(wrench)
            kind: other
        when:
            files-changed:
                - 'gfx/wr/**'

    wrench-macos-build:
        description: Cross compilation of wrench for macOS on Linux
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: webrender}
            chain-of-trust: true
            artifacts:
                - type: file
                  name: public/build/wrench-macos.tar.bz2
                  path: /builds/worker/artifacts/wrench-macos.tar.bz2
                - type: file
                  name: public/build/wrench-macos-headless.tar.bz2
                  path: /builds/worker/artifacts/wrench-macos-headless.tar.bz2
        dependencies:
            macosx64-clang-14: toolchain-macosx64-clang-14-raw
        fetches:
            toolchain:
                - linux64-rust-macos
                - linux64-clang-14
                - macosx64-sdk
                - wrench-deps
            macosx64-clang-14:
                - artifact: clang.tar.zst
                  dest: clang-mac
        run:
            using: run-task
            command: '$HOME/checkouts/gecko/taskcluster/scripts/misc/wrench-macos-build.sh'
        treeherder:
            platform: osx-cross/opt
            symbol: WR(B)
        when:
            files-changed:
                - 'gfx/wr/**'
                - 'taskcluster/scripts/misc/wr-macos-cross-build-setup.sh'
                - 'taskcluster/scripts/misc/wrench-macos-build.sh'

    macos-release:
        description: Runs release-mode WebRender CI tests on a macOS worker
        worker-type: t-osx-1015-r8
        worker:
            # repo cloning has highly variable run time
            max-run-time: 7200
            env:
                MOZ_FETCHES_DIR: 'checkouts/gecko/gfx/wr'
        dependencies:
            webrender-wrench-macos-build: webrender-wrench-macos-build
        fetches:
            webrender-wrench-macos-build:
                - 'wrench-macos.tar.bz2'
                - 'wrench-macos-headless.tar.bz2'
        run:
            using: run-task
            cwd: '{checkout}/gfx/wr'
            command: >-
                export WRENCH_HEADLESS_TARGET=$PWD/wrench-macos-headless/ &&
                export WRENCH_BINARY=$PWD/wrench-macos/bin/wrench &&
                ci-scripts/macos-release-tests.sh
        treeherder:
            platform: macosx1015-64-qr/opt
            symbol: WR(wrench)
        when:
            files-changed:
                - 'gfx/wr/**'

    cargotest-macos-build:
        description: Cross compilation of cargo tests for macOS on Linux
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: webrender}
            chain-of-trust: true
            artifacts:
                - type: file
                  name: public/build/cargo-test-binaries.tar.bz2
                  path: /builds/worker/artifacts/cargo-test-binaries.tar.bz2
        fetches:
            toolchain:
                - linux64-rust-macos
                - linux64-clang
                - macosx64-sdk
                - wrench-deps
        run:
            using: run-task
            command: '$HOME/checkouts/gecko/taskcluster/scripts/misc/wr-cargotest-macos-build.sh'
        treeherder:
            platform: osx-cross/debug
            symbol: WR(B)
        when:
            files-changed:
                - 'gfx/wr/**'
                - 'taskcluster/scripts/misc/wr-cargotest-macos-build.sh'
                - 'taskcluster/scripts/misc/wr-macos-cross-build-setup.sh'

    macos-debug:
        description: Runs debug-mode WebRender CI tests on a macOS worker
        worker-type: t-osx-1015-r8
        worker:
            max-run-time: 3600
            env:
                MOZ_FETCHES_DIR: 'checkouts/gecko/gfx/wr'
        dependencies:
            webrender-cargotest-macos-build: webrender-cargotest-macos-build
        fetches:
            webrender-cargotest-macos-build:
                - 'cargo-test-binaries.tar.bz2'
        run:
            using: run-task
            cwd: '{checkout}/gfx/wr'
            command: >-
                mv cargo-test-binaries target &&
                cd target &&
                for i in debug/deps/*; do $i; done
        treeherder:
            platform: macosx1015-64-qr/debug
            symbol: WR(cargotest)
        when:
            files-changed:
                - 'gfx/wr/**'

    windows:
        description: Runs WebRender CI tests on a Windows worker
        worker-type: win11-64-2009-source
        worker:
            max-run-time: 5400
            env:
                NODE_OPTIONS: '--max_old_space_size=4096'
        fetches:
            toolchain:
                - win64-rust
                - vs
                - wrench-deps
        run:
            using: run-task
            use-caches: false
            command: '$GECKO_PATH/taskcluster/scripts/misc/wrench-windows-tests.sh'
        treeherder:
            platform: windows11-64-2009-qr/release
            symbol: WR(wrench)
        when:
            files-changed:
                - 'build/win64/mozconfig.vs2019'
                - 'gfx/wr/**'
                - 'taskcluster/scripts/misc/wrench-windows-tests.sh'
